// Syncs the compiled ABI + deployment addresses from contracts/ into src/lib/contracts/.
// Run after `forge build` / deployment:  node scripts/sync-abi.mjs
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(root, "..");
const artifact = JSON.parse(
  readFileSync(path.join(repo, "contracts/out/HabibiPropertyPools.sol/HabibiPropertyPools.json"), "utf8"),
);

const deployments = {};
const depDir = path.join(repo, "contracts/deployments");
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir)) {
    if (!f.endsWith(".json")) continue;
    const d = JSON.parse(readFileSync(path.join(depDir, f), "utf8"));
    deployments[d.chainId] = { address: d.contract, deployBlock: d.block };
  }
}

const outDir = path.join(repo, "src/lib/contracts");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "habibiPropertyPools.ts"),
  `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Source: contracts/src/HabibiPropertyPools.sol (forge build artifact).

export const habibiPropertyPoolsAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;

/** Deployed addresses per chain id (from contracts/deployments/*.json). */
export const habibiPropertyPoolsDeployments: Record<number, { address: \`0x\${string}\`; deployBlock: number }> = ${JSON.stringify(deployments, null, 2)} as const;
`,
);
console.log("synced ABI +", Object.keys(deployments).length, "deployment(s)");
