// Syncs the compiled ABI + deployment addresses from contracts/ into src/lib/contracts/.
// Run after `forge build` / deployment:  node scripts/sync-abi.mjs
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(root, "..");
const outDir = path.join(repo, "src/lib/contracts");
mkdirSync(outDir, { recursive: true });

/** Collect deployments matching a filename prefix (or the default set). */
function collectDeployments(prefix) {
  const out = {};
  const depDir = path.join(repo, "contracts/deployments");
  if (!existsSync(depDir)) return out;
  for (const f of readdirSync(depDir)) {
    if (!f.endsWith(".json")) continue;
    const isCampaign = f.startsWith("campaigns-");
    if (prefix === "campaigns" ? !isCampaign : isCampaign) continue;
    const d = JSON.parse(readFileSync(path.join(depDir, f), "utf8"));
    out[d.chainId] = { address: d.contract, deployBlock: d.block };
  }
  return out;
}

function emit(contractName, exportBase, deployments) {
  const artifact = JSON.parse(
    readFileSync(path.join(repo, `contracts/out/${contractName}.sol/${contractName}.json`), "utf8"),
  );
  writeFileSync(
    path.join(outDir, `${exportBase}.ts`),
    `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Source: contracts/src/${contractName}.sol (forge build artifact).

export const ${exportBase}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;

/** Deployed addresses per chain id (from contracts/deployments/*.json). */
export const ${exportBase}Deployments: Record<number, { address: \`0x\${string}\`; deployBlock: number }> = ${JSON.stringify(deployments, null, 2)} as const;
`,
  );
  return Object.keys(deployments).length;
}

const n1 = emit("HabibiPropertyPools", "habibiPropertyPools", collectDeployments("pools"));
const n2 = emit("HabibiCampaigns", "habibiCampaigns", collectDeployments("campaigns"));
console.log(`synced ABIs — pools(${n1} deployment(s)), campaigns(${n2} deployment(s))`);
